export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";
export const CHANEG_HOT_RECOMMENDS = "CHANEG_HOT_RECOMMENDS";
export const CHANGE_NEW_ALBUM ="CHANGE_NEW_ALBUM"
export const CHANGE_UP_RANKINGS= "CHANGE_UP_RANKINGS"
export const CHANGE_NEW_RANKINGS ="CHANGE_NEW_RANKINGS"
export const CHANGE_ORIGIN_RANKINGS = "CHANGE_ORIGIN_RANKINGS"
export const CHANGE_SETTLEARTIST ="CHANGE_SETTLEARTIST"