export const CHANGE_SONGS = "PLAYER/CHANGE_SONGS";
export const CHANGE_PLAYLIST = "PLAYER/CHANGE_PLAYLIST";
export const CHANGE_CURRENT_SONG_INDEX = "PLAYER/CHANGE_CURRENTSONGINDEX";
export const CHANGE_SEQUENCE = "PLAYER/CHANGE_SEQUENCE";
export const CHANGE_LYRICS = "PLAYER/HANGE_LYRICS";
export const CHANGE_CURRENT_LYRICS_INDEX = "PLAYER/CHANGE_CURRENT_LYRICS_INDEX";    