export const CHANGE_CATEGORY = "SONGS/CHANGE_CATEGORY"
export const CHANGE_CURRENT_CATEGORY ="SONGS/CHANGE_CURRENT_CATEGORY"
export const CHANGE_CATEGORY_SONGS_LIST = 'SONGS/CHANGE_CATEGORY_SONGS_LIST'    
export const PER_PAGE_NUMBER = 35;
